# Configuración de Black
[tool.black]
line-length = 99
target-version = ["py310"]

# Configuración de isort
[tool.isort]
profile = "black"
line_length = 99
skip_gitignore = true
known_local_folder = [
    "gpt_dialog",
    "tests",
]
